### ISSUE TITLE
FAX memory leak

### ISSUE THREAD

**Issue by feigaodm** [XENON1T/pax#575] opened 2017-05-25 19:33 UTC
@darrylmasson discovered a memory leak in fax but we are still not sure which plugin does it. Here is a plot @darrylmasson created to test the memory usage as a function of time.
![memory_usage_darryl](https://cloud.githubusercontent.com/assets/18223253/26467111/3e0c798a-415f-11e7-94d9-d2810f8f29e4.png)

@darrylmasson  concluded that fax's memory usage climbed at 16.7 +/- 1.0 MB/minute while pax's memory usage remained flat. 

It would be great if fax developers @mcfatelin @JelleAalbers can take a look and fix it.

**Comment by darrylmasson** [comment] 2017-05-25 19:46
The fax instruction set I used for this is 1000 lines of '%i,ER,random,random,random,4913,2403,5e5'. I ran several instances of fax to make waveforms, then turned around and ran pax on them (separate calls to the executable).

**Comment by mcfatelin** [comment] 2017-05-25 20:15
@darrylmasson can you please try disable PMT after pulse, photoionization and noise one by one, to see if one of them is the cause. Then it will be easier to find the lines in code responsible.

**Comment by darrylmasson** [comment] 2017-05-26 13:32
I ran four jobs disabling PI, AP, and noise individually
![fax_mem_split](https://cloud.githubusercontent.com/assets/10812861/26496508/cf4c8e44-41f5-11e7-8da5-84c985314f7a.png)


Memory usage: no AP: 16.9 MB/min, no noise: 11.6 MB/min, no PI: 3.1 MB/min.
PI seems to be the worst culprit. Also, disabling PI dramatically increases the processing rate.

**Comment by mcfatelin** [comment] 2017-05-30 17:44
@darrylmasson Thanks very much. Unfortunately looks like the memory leak is in S1 and S2 simulation then. Can you please help do one more check? Simulation with S1-only & S2-only (you can disable AP and PI for the test).

**Comment by sthapa** [comment] 2017-05-30 17:49
I did some quick testing on Thursday and Friday with [pympler](https://pythonhosted.org/Pympler/muppy.html#the-tracker-module) to see if I could help with locating the memory leak.  Not sure if this helps or not but here's what I found.

I changed pax/core.py to instrument it and to try to track any leaking memory usage as follows:

```
    def process_event(self, event):
        """Process one event with all action plugins. Returns processed event."""
        total_plugins = len(self.action_plugins)

        for j, plugin in enumerate(self.action_plugins):
            self.log.debug("%s (step %d/%d)" % (plugin.__class__.__name__, j, total_plugins))
            tr = tracker.SummaryTracker()
            event = plugin.process_event(event)
            gc.collect()
            print("%s (step %d/%d) Summary Tracker diff" % (plugin.__class__.__name__, j, total_plugins))
            tr.print_diff()
            plugin.total_time_taken += self.timer.punch()
        # Uncomment to diagnose memory leaks
        gc.collect()  # don't care about stuff that would be garbage collected properly
        # objgraph.show_growth(limit=5)
        return event
```

Would getting the results from this run be helpful or is this a red herring?

**Comment by pdeperio** [comment] 2017-05-30 18:09
Thanks @sthapa.  I'm not sure exactly if ```process_event``` is also used for the fax simulation stage/plugins (which @darrylmasson has isolated the problem to); @JelleAalbers can you comment?

You can still try with the ```paxer``` option 
```
--config XENON1T reduce_raw_data SimulationMCInput 
```
to run only fax mode.

The simulation plugins are [simulation.py](https://github.com/XENON1T/pax/blob/master/pax/simulation.py) and [WaveformSimulator.py](https://github.com/XENON1T/pax/blob/master/pax/plugins/io/WaveformSimulator.py)

**Comment by sthapa** [comment] 2017-05-30 18:39
Here's an example of the output from pympler / muppy .  This shows  the new python objects the after the FindHits plugin was called.  Adding and obtaining information like this for other code would not be difficult, I just need to know which functions to instrument in order to track memory changes.

```
FindHits (step 5/30) Summary Tracker diff
                                   types |   # objects |   total size
======================================== | =========== | ============
                   <class 'numpy.ndarray |           1 |      3.67 MB
                            <class 'code |           1 |    144     B
                   function (store_info) |           1 |    136     B
                            <class 'cell |           2 |     96     B
                             <class 'str |           1 |     87     B
                           <class 'bytes |           1 |     74     B
                           <class 'tuple |           0 |      8     B
                            <class 'list |           0 |      8     B
  <class 'pympler.tracker.SummaryTracker |          -1 |    -56     B
                          <class 'method |          -1 |    -64     B
                            <class 'dict |          -1 |   -288     B
```

**Comment by darrylmasson** [comment] 2017-05-30 19:10
Running s1 only or s2 only with PI and AP disabled for both yields flat memory usage. I'll run again with PI turned back on as that was the main culprit.

**Comment by mcfatelin** [comment] 2017-05-30 19:25
@darrylmasson Sorry I misinterpreted your plot. So PI actually contributes a lot to the memory increasing. I suspect it can be due to the fact that fax is outputting PI info as well, which can be huge if the S2 is very large [See here](https://github.com/XENON1T/pax/blob/master/pax/plugins/io/WaveformSimulator.py#L251). I'll put a flag in the [new fax PR](https://github.com/XENON1T/pax/pull/574).

**Comment by feigaodm** [comment] 2017-06-01 18:48
@darrylmasson Could you please checkout the latest version and check this again to see whether it's fixed? Thanks

**Comment by sthapa** [comment] 2017-06-01 20:10
@pdeperio here's a summarized view of potential memory leaks from the processEvent method using the config options you mentioned.   It looks like a a PulseData object might be leaking on for each event that gets processed.  

```
process_event Summary Tracker diff
                                   types |   # objects |   total size
======================================== | =========== | ============
                            <class 'list |       17103 |      1.77 MB
         <class 'pax.datastructure.Pulse |       26338 |      1.41 MB
                             <class 'str |       17105 |      1.21 MB
                             <class 'int |        3622 |     99.11 KB
                            <class 'dict |          26 |      7.00 KB
              <class '_io.BufferedWriter |           1 |      4.17 KB
              <class 'wrapper_descriptor |          35 |      2.73 KB
                         <class 'weakref |          21 |      1.64 KB
               <class 'method_descriptor |          12 |    864     B
                            <class 'type |           0 |    384     B
                 <class 'zipfile.ZipInfo |           1 |    192     B
  <class 'pax.plugin.EventLoggingAdapter |           3 |    168     B
                   function (store_info) |           1 |    136     B
      <class 'numba.types.npytypes.Array |           2 |    112     B
                           <class 'bytes |           2 |    101     B
process_event Summary Tracker diff
                                 types |   # objects |   total size
====================================== | =========== | ============
       <class 'pax.datastructure.Pulse |       47696 |      2.55 MB
                          <class 'list |       17105 |      1.96 MB
                           <class 'str |       17106 |      1.21 MB
                           <class 'int |        3601 |     98.47 KB
               <class 'zipfile.ZipInfo |           1 |    192     B
                          <class 'code |           1 |    144     B
                 function (store_info) |           1 |    136     B
                          <class 'cell |           2 |     96     B
  <class 'pax.datastructure.EventProxy |           1 |     72     B
                         <class 'bytes |           1 |     67     B
                         <class 'tuple |           0 |      8     B
                        <class 'method |          -1 |    -64     B
                          <class 'dict |           0 |    -96     B
process_event Summary Tracker diff
                                 types |   # objects |   total size
====================================== | =========== | ============
                          <class 'list |       17105 |      1.74 MB
                           <class 'str |       17106 |      1.21 MB
       <class 'pax.datastructure.Pulse |       20620 |      1.10 MB
                           <class 'int |        3601 |     98.47 KB
               <class 'zipfile.ZipInfo |           1 |    192     B
                          <class 'code |           1 |    144     B
                 function (store_info) |           1 |    136     B
                          <class 'cell |           2 |     96     B
  <class 'pax.datastructure.EventProxy |           1 |     72     B
                         <class 'bytes |           1 |     67     B
                         <class 'tuple |           0 |      8     B
                        <class 'method |          -1 |    -64     B
                          <class 'dict |           0 |    -96     B
```

**Comment by darrylmasson** [comment] 2017-06-01 22:11
Some preliminary tests show memory usage increasing at ~1 MB/s, which is an order of magnitude better. I'll collect more data and post a plot tomorrow.

**Comment by feigaodm** [comment] 2017-06-01 22:17
Thanks @darrylmasson , I guess you meant ~1MB/min? Maybe there is another memory leak in pax Pulse module as @sthapa showed. Probably this is good enough for now but we have to keep an eye on it.

**Comment by darrylmasson** [comment] 2017-06-02 13:23
![fax_patched](https://cloud.githubusercontent.com/assets/10812861/26727446/ecdabdb2-4774-11e7-8ad1-647a9e201638.png)
Average 1.25 MB/min after the first few minutes. Still not ideal but much more sustainable that >15 MB/min.

**Comment by sthapa** [comment] 2017-06-02 17:39
Looking at the growth that should be workable on OSG.  You could size jobs for a 2 hour runtime without exceeding 2GB.  It'll probably also be okay on Comet with 10 hour jobs.

**Comment by darrylmasson** [comment] 2017-06-13 14:04
In lieu of any further developments on this issue, I'll close it for now.

**Closed by darrylmasson** 2017-06-13 14:04 UTC
Labels: bug, enhancement
