### ISSUE TITLE
Could not find the real data member 'area_per_channel'

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#353] opened 2016-05-02 16:39 UTC
Possible ROOT internal issue which may be a bit more dangerous since it looks like the process completed happily:

https://gist.github.com/pdeperio/5ff2dcf22b4f94f613d1fc993c95372c
```
Status: processing_done. Processing queue: 0 events. Output queue: 0 events. RAM usage: 372.9 (master) 0.0 (workers) 385.3 (output)Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/rootpy/logger/roothandler.py", line 123, in python_logging_error_handler
    log.CRITICAL("abort().. expect a stack trace")
TypeError: 'int' object is not callable
```

Dataset: 160501_1343
Run: 339

and
https://gist.github.com/pdeperio/775fab31c5f46b547a2ba17fb207cdcc
Dataset: 160422_1731
Run: 170

**Comment by sanderbreur** [comment] 2016-05-02 16:46
Yes that is a bit dangerous as I just looked at the root file
of 160501_1343 and it is an empty root file with 44k empty events ;)

s

Op ma 2 mei 2016 om 18:39 schreef Patrick de Perio <notifications@github.com

**Comment by JelleAalbers** [comment] 2016-05-02 17:15
Run 160501_1343 is one of the runs affected by #352. 

Run 170 seems fine, I just checked the root file on midway, it looks like it contains peaks with actual areas etc?

**Comment by pdeperio** [comment] 2016-05-02 18:31
So more cases:

```
Dataset: 160502_1129
Run: 362

Dataset: 160502_1229
Run: 364

Dataset: 160502_1301
Run: 366
```

Both also failed first time with:
```AttributeError: 'vector<Hit,allocator<Hit> >' object has no attribute 'clear'```

then completed second time with 
```TypeError: 'int' object is not callable```
and seems fine (ROOT file has info).

So seems like a transient issue...

**Comment by JelleAalbers** [comment] 2016-05-17 06:15
Are you still observing these issues after 4.9.2?

**Comment by pdeperio** [comment] 2016-05-17 13:55
looks like none in 4.9.3

**Comment by pdeperio** [comment] 2016-05-20 18:26
actually, maybe it's still occurring for LED data, just noticed with v4.10.0:

```
ROOT.TBranchElement.InitializeOffsets Process-8  L98 CRITICAL Could not find the real data member 'area_per_channel' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/project/lgrandi/anaconda3/envs/pax_v4.10.0/lib/python3.4/site-packages/rootpy/logger/roothandler.py", line 123, in python_logging_error_handler
    log.CRITICAL("abort().. expect a stack trace")
TypeError: 'int' object is not callable
ROOT.TBranchElement.InitializeOffsets Process-8  L98 CRITICAL Could not find the real data member 'hits_per_channel' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/project/lgrandi/anaconda3/envs/pax_v4.10.0/lib/python3.4/site-packages/rootpy/logger/roothandler.py", line 123, in python_logging_error_handler
    log.CRITICAL("abort().. expect a stack trace")
TypeError: 'int' object is not callable
ROOT.TBranchElement.InitializeOffsets Process-8  L98 CRITICAL Could not find the real data member 'n_saturated_per_channel' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/project/lgrandi/anaconda3/envs/pax_v4.10.0/lib/python3.4/site-packages/rootpy/logger/roothandler.py", line 123, in python_logging_error_handler
    log.CRITICAL("abort().. expect a stack trace")
TypeError: 'int' object is not callable
ROOT.TBranchElement.InitializeOffsets Process-8  L98 CRITICAL Could not find the real data member 'sum_waveform' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/project/lgrandi/anaconda3/envs/pax_v4.10.0/lib/python3.4/site-packages/rootpy/logger/roothandler.py", line 123, in python_logging_error_handler
    log.CRITICAL("abort().. expect a stack trace")
TypeError: 'int' object is not callable
ROOT.TBranchElement.InitializeOffsets Process-8  L98 CRITICAL Could not find the real data member 'sum_waveform_top' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
```

**Comment by JelleAalbers** [comment] 2016-05-29 12:51
The 'int' object is not callable TypeError is caused by a typo in rootpy, they should have written log.critical instead (log.CRITICAL is a constant denoting a log level). 

I'm more worried about the "Could not find the real data member" error, the most helpful comment I could find was [this](https://root.cern.ch/root/html/src/TBranchElement.cxx.html#3173) from the root source code...

**Comment by JelleAalbers** [comment] 2016-05-29 12:56
Actually there seem to be a few ROOT bugs on this topic:
https://sft.its.cern.ch/jira/browse/ROOT-5983
https://sft.its.cern.ch/jira/browse/ROOT-5739
https://sft.its.cern.ch/jira/browse/ROOT-5628

The first one in particular seem similar to what we're doing, and is unresolved. Of course this doesn't explain why the issue occurs only some of the time. Maybe upgrading the

**Comment by rizzoa** [comment] 2016-05-30 11:13
Hi @JelleAalbers , I am reprocessing DM run 10 data on GRID and I have encountered kind of the same error,
.....
TypeError: 'int' object is not callable
ROOT.TBranchElement.InitializeOffsets MainProcess L98 CRITICAL Could not find the real data member 'hits_per_channel' when constructing the branch 'peaks' [Likely an internal error, please report to the developers].
Traceback (most recent call last):
..................

I am using PAX version 4.4.0 and ROOT version 5.34-32, so I don't know if the error @pdeperio see on the other version of PAX has the some origin. Anyway, at least for this error, I can say that it raises when a particular XED files are trying to created a new rootpy cache. But if before a "good" XED file was processed with a creation of a rootpy cache, then the "bad" XED file will be processed afterwards with no error.  On the GRID I am processing a bunch of 50 XED files in one jobs, so this means that if the first XED file is problematic, the processing of the other files will fail. I can reproduce this issue on xe-grid00 and xecluster06 as well.

**Comment by JelleAalbers** [comment] 2016-05-30 17:49
Hi Alfio, I would first suggest upgrading pax to the latest version, there were significant improvements to the ROOT output and multiprocessing support since 440 (see #323 and #351 in particular). It may or may not fix the problem you're having but will be helpful in diagnosing what's going on.

**Comment by rizzoa** [comment] 2016-05-30 18:16
Hi Jelle, I see. I have already tested pax_head version on xe-grid00,  which is 4.10.1 with root6. I have still issue (different than the int callable) but on the same XED file. Apparently this version of pax_head version rebuild everytime the rootpy cache while it was not the case of the one on GRID. We will go in details tomorrow,  I will give you the recipe to reproduce the issue with both PAX versions.

**Comment by rizzoa** [comment] 2016-06-01 12:39
@JelleAalbers Here the recipe how to reproduce the issue. You can do in xe-grid00/01 or on xecluster06. 
PAX 440 and ROOT 5

- source /archive_lngs/common/anaconda3/bin/activate pax440r5
- remove the rootpy cache in .cache
- copy a problematic XED file in your directory, e.g. 
/archive/data/xenon100/run_10/xe100_110302_1945/xe100_110302_1945_000350.xed
- process with PAX, paxer --input xe100_110302_1945_000350.xed --output xe100_110302_1945_000350 --config XENON100 (new shared libraries are created)
- You should get the famous TypeError: 'int' object is not callable
- copy a good XED file, e.g.
/archive/data/xenon100/run_10/xe100_110302_1945/xe100_110302_1945_000351.xed
- Processing with PAX will fail with same error (using the same shared libraries)
But if you
- remove the rootpy cache
- Process first the good XED file, it will finish ok (new shared libraries)
- Then  processing the XED problematic file will finish also ok (with the same shared libraries)

**Comment by rizzoa** [comment] 2016-06-01 12:49
@JelleAalbers here the error I got if I setup pax_head instead
but the same problematic XED file as above
.....
ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL

Doing the trick to process before the good XED file will not help sine this version of PAX will always create rootpy share libraries.

With both PAX versions, I am not doing any multiprocessing, just one job --> one CPU

**Comment by JelleAalbers** [comment] 2016-06-01 15:03
Thanks a lot for the detailed report Alfio, now I finally realize what the problem is! That XED file starts with this event:

![figure_1](https://cloud.githubusercontent.com/assets/4354311/15714395/a28fddd4-281a-11e6-891f-3f504e5a9bd6.png)

which does not contain any peaks. In this case the root class did not get created properly, since pax does not set some array sizes. More info is in #370.

**Comment by rizzoa** [comment] 2016-06-01 15:48
@JelleAalbers thanks to have find a solution to this issue. But I need to find some workaround for GRID. We used PAX 440 root5 to reprocess the data, and I don't know if make sense to use a newer version just for a partial amount of data. Just a matter to be coherent....,maybe I have some idea...

**Comment by tunnell** [comment] 2016-06-01 15:52
At least we understand the issue now.  It's fine to skip a file if we account for it in the lifetime.  Agree @pdeperio ?

**Comment by tunnell** [comment] 2016-06-01 15:52
Can close once pull request merged.

**Comment by rizzoa** [comment] 2016-06-01 15:56
@tunnell are you going to update pax_head on xecluster ?

**Comment by tunnell** [comment] 2016-06-01 15:57
once Jelle's proposed changes get merged.  Needs to pass tests and I'll look at it asap.

**Comment by rizzoa** [comment] 2016-06-01 15:59
OK

**Closed** 2016-06-01 16:02 UTC
Labels: bug, processed data io
